export enum CONVERT_VIETNAMESE {
  LOGGEDIN = "LOGGED_IN",
  NOTLOGGEDIN = "NOT_LOGGED_IN",
}

export enum SEARCH_USER_DATE_TYPE {
  CREATE_AT = "createdAt",
  LAST_VISIT_DATE = "lastVisitDate",
}

export enum STATISTIC_STATUS_LOGIN {
  LOGGED_IN = "LOGGED_IN",
  NOT_LOGGED_IN = "NOT_LOGGED_IN",
}

export enum SEARCH_STATUS_RECEIVE_GIFT {
  RECEIVED = "RECEIVED",
  NOT_RECEIVED = "NOT_RECEIVED",
}

export enum EVENT_TYPE {
  REWARD_POINT = "REWARD_POINT",
  REWARD_GIFT = "REWARD_GIFT",
  SELECT_GIFT = "SELECT_GIFT",
}
